name: coreapp
description: Base geral para App Loja Online.


publish_to: 'none' 


version: 0.1.0


environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  image_picker: ^0.6.7+4
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.4.10
  path_provider: ^1.6.10
  transparent_image: ^1.0.0
  carousel_pro: ^1.0.0
  firebase: ^7.3.0
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.6
  shared_preferences: ^0.5.7+3
  get: ^2.11.3
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^1.2.5+1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  
scripts:
  mobx: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs
  build_apk: flutter pub get & flutter build apk -t lib/main_production.dart --release
  build_web: flutter pub get & flutter build web -t lib/main_production.dart --release
